Switch package type to module
With commit b972284 ("Rename ESM files to use `.js` extension"), ESM
imports now fail with:

import { Request, Headers } from "@libsql/isomorphic-fetch";
                  ^^^^^^^
SyntaxError: Named export 'Headers' not found. The requested module '@libsql/isomorphic-fetch' is a CommonJS module, which may not support all module.exports as named exports.

Fix that up.